apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  releaseName: tailscale
  chart:
    spec:
      chart: tailscale
      sourceRef:
        kind: HelmRepository
        name: tailscale
  interval: 50m
  install:
    remediation:
      retries: 3
