apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: identify
  namespace: card-sorter
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: identify
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
