---
# Personal Site uses nodemailer to send emails
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: contact-me-gmail-account-details
  namespace: personal-site
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: contact-me-gmail-account-details
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: contact_me_gmail_account_details
        property: username
    - secretKey: password
      remoteRef:
        key: contact_me_gmail_account_details
        property: password
