---
# Harbor admin password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: harbor-admin-password
    creationPolicy: Owner
  data:
    - secretKey: harborAdminPassword
      remoteRef:
        key: k3s_harbor_admin_password
