---
# Harbor admin password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-oauth-client
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: tailscale-oauth-client
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: k3s_tailscale_oauth
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: k3s_tailscale_oauth
        property: client_secret
