apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth-client
      valuesKey: client_id
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-oauth-client
      valuesKey: client_secret
      targetPath: oauth.clientSecret
    